clear; clc; close all;

fprintf('================================================\n');
fprintf(' Unmanned Rendezvous Mission 6-DOF Simulator\n');
fprintf('================================================\n\n');

%% 1. Initialization
sys = Mission_Config();
mission_cfg = load_mission_json_config_local();
sys = apply_json_to_sys_local(sys, mission_cfg);
sys = apply_environment_env_overrides_local(sys);
print_environment_config_local(sys);

% Budget Tracking Table
Budget = table('Size',[0 4], 'VariableTypes',{'string','double','double','double'}, ...
    'VariableNames',{'Phase','DeltaV_ms','Fuel_Consumed_kg','Remaining_Mass_kg'});

m_current = sys.Chaser_Mass_Init;
initial_chaser_angle = get_json_angle_rad_local(mission_cfg, {'scenario','initial_chaser_angle_deg'}, 0);
initial_phase_angle = get_json_angle_rad_local(mission_cfg, {'scenario','initial_phase_angle_deg'}, pi/2);

% Initial chaser state.
[x_insert, v_insert_vec] = circular_polar_state_local(sys.Re + sys.h_insert, initial_chaser_angle, sys);
X_chaser_init = [x_insert;  v_insert_vec;  0;0;0;1;  0;0;0;  m_current];
target_radius = sys.Re + sys.h_wait;

% Initial target state.
[x_target, v_target_vec] = circular_polar_state_local(sys.Re + sys.h_target, initial_chaser_angle + initial_phase_angle, sys);
X_target = [x_target; v_target_vec];

%% 2. Phase 1: Phasing & Homing
fprintf('[Phase 1] 3-DOF phasing propagation start (J2 included)...\n');

% Default Phase 1 custom-maneuver settings. A JSON config exported by the
% Python optimizer can override these values without editing this script.
custom_params = struct();

% Parameters for CUSTOM_IMPULSE mode. These are normally generated by the
% Python shooting optimizer.
% custom_params.phase_angle = deg2rad(3.8242);        % [rad]
% custom_params.delta_v     = 57.9955;                % [m/s]
% custom_params.gamma       = deg2rad(0.076877);      % [rad]

custom_params.phase_angle = deg2rad(3.5663);        % [rad]
custom_params.delta_v     = 64.2342;                % [m/s]
custom_params.gamma       = deg2rad(-1.416);        % [rad]

custom_params.phase_angle_unit = "rad"; % "rad" or "deg"
custom_params.gamma_unit       = "rad"; % "rad" or "deg"

% Maneuver execution model for the custom phased maneuver.
% Use "IMPULSIVE" for the legacy instantaneous delta-V model or
% "FINITE_BURN" to execute the same delta-V over a short high-thrust burn.
% phase_angle, delta_v, and gamma parameters.
custom_params.burn_model = sys.maneuver.default_burn_model;
burn_model_env = strtrim(string(getenv('RENDEZVOUS_BURN_MODEL')));
if strlength(burn_model_env) > 0
    custom_params.burn_model = upper(burn_model_env);
end
custom_params.burn_direction_mode = sys.maneuver.direction_mode;
custom_params.finite_burn_thrust = sys.maneuver.finite_burn_thrust; % [N]
custom_params.finite_burn_isp = sys.maneuver.finite_burn_isp;       % [s]
custom_params.dt_burn = sys.maneuver.finite_burn_dt;                % [s]
custom_params.max_single_burn_duration = sys.maneuver.max_single_burn_duration; % [s]
custom_params.max_single_burn_delta_v = sys.maneuver.max_single_burn_delta_v;   % [m/s]
custom_params.use_thrust_noise = false;
custom_params.multi_hohmann_legs = []; % [] lets MULTI_HOHMANN choose from thermal limits.

% Phase 1 target relative position in the target LVLH frame [m].
custom_params.desired_rel_lvlh = [0; -5000; 0];

% Event detection and propagation settings.
custom_params.time_step = 10;           % [s] nominal propagation step
custom_params.dt_phase = 5;             % [s] coarse phase-angle detection step
custom_params.dt_capture = 5;           % [s] coarse capture detection step
custom_params.max_wait = 2*pi * sys.mu^(-0.5) / ((sys.Re + sys.h_insert)^(-1.5) - (sys.Re + sys.h_target)^(-1.5));
custom_params.max_capture_time = 30000; % [s] maximum post-burn capture search time
custom_params.phase_tol = 1e-7;         % [rad] phase-angle event tolerance
custom_params.event_time_tol = 1e-3;    % [s] event refinement tolerance
custom_params.capture_pos_tol = 0.5;    % [m] capture tolerance about desired_rel_lvlh
custom_params.min_capture_time = 0;     % [s] raise to ignore very early local minima

% Mode options: "CUSTOM_IMPULSE", "HOHMANN", "MULTI_HOHMANN"
phasing_mode = "CUSTOM_IMPULSE";
[phasing_mode, custom_params] = apply_json_to_phase1_local(phasing_mode, custom_params, mission_cfg);

[X_chaser, dV_p1, fuel_p1, hist_p1, X_target] = Phasing_Propagator(sys, X_chaser_init, target_radius, phasing_mode, custom_params, X_target, 1);
m_current = X_chaser(14);

Budget = [Budget; {"Phase 1: "+phasing_mode, dV_p1, fuel_p1, m_current}];

if isfield(hist_p1, 'maneuver_duration') && ~isempty(hist_p1.maneuver_duration)
    max_burn_duration_p1 = max(hist_p1.maneuver_duration);
    max_burn_delta_v_p1 = max(hist_p1.maneuver_delta_v);
    fprintf('   Phase 1 max burn duration: %.3f s\n', max_burn_duration_p1);
    fprintf('   Phase 1 max single-burn delta-V: %.6f m/s\n', max_burn_delta_v_p1);
end

h_vec_p1 = cross(X_target(1:3), X_target(4:6));
i_u_p1 = X_target(1:3)/norm(X_target(1:3));
k_u_p1 = h_vec_p1/norm(h_vec_p1);
j_u_p1 = cross(k_u_p1, i_u_p1);
C_I2L_p1 = [i_u_p1'; j_u_p1'; k_u_p1'];
rel_p1_lvlh = C_I2L_p1 * (X_chaser(1:3) - X_target(1:3));
miss_p1 = norm(rel_p1_lvlh - custom_params.desired_rel_lvlh);

fprintf('   Phase 1 terminal LVLH relative position: [%+.3f, %+.3f, %+.3f] m\n', rel_p1_lvlh(1), rel_p1_lvlh(2), rel_p1_lvlh(3));
fprintf('   desired_rel_lvlh error: %.6f m\n', miss_p1);
fprintf('   Phase 1 terminal altitude: %.2f km\n', (norm(X_chaser(1:3)) - sys.Re)/1000);

%% 3. Phase 2: +R-bar Approach & Berthing (Waypoint-Impulse Simulation)
fprintf('\n[Phase 2] Starting waypoint-impulsive +R-bar approach...\n');

% -------------------------------------------------------------------------
% Phase 2 concept
%   - S2:  -V-bar 5 km hold point, inherited from Phase 1 when possible.
%   - S2 -> S3: one retrograde/-V-bar impulse, then free cycloidal drift.
%       * v0 is selected from |delta_R|max = 4*v0/n.
%       * S3 is not pre-fixed. S3 is the first point where V-bar coordinate
%         crosses zero after the cycloidal drift starts.
%   - S3 -> S4: short two-impulse R-bar hops. Each hop uses CW targeting for
%     the departure impulse, nonlinear Env_EOM propagation, then a small
%     braking impulse to hold before the next hop.
%   - No state overwriting: all corrections are impulses + free propagation.
% -------------------------------------------------------------------------
p2 = struct();
p2.dt = 1.0;                         % [s] propagation step during proximity ops
p2.S2 = [0; -5000; 0];               % [m] -V-bar hold point after Phase 1
p2.S3 = [NaN; NaN; NaN];             % [m] determined by first V-bar crossing
p2.S4_R_abs = 30;                    % [m] final stand-off distance on the same R-bar side as S3
p2.S4 = [NaN; NaN; NaN];             % [m] determined after S3 is detected
p2.initial_S2_tol = 50.0;            % [m] if Phase 1 is farther, insert cleanup leg to S2
p2.tof_initial_s2 = 1200;            % [s] cleanup transfer time to S2, only used if needed
p2.delta_R_cycloid = 400;            % [m] maximum radial excursion magnitude for the cycloid
p2.vbar_burn_sign = -1;              % -1 means apply the S2 impulse in the -V-bar direction
p2.vbar_cross_tol = 1.0;             % [m] acceptable error for detecting first V-bar crossing
p2.max_cycloid_orbits = 4.0;         % safety limit for S2->S3 free drift
p2.rbar_hop_count = 8;               % number of S3->S4 R-bar hops
p2.tof_hop = 300;                    % [s] transfer time per R-bar hop
p2.capture_pos_tol = 0.25;           % [m] terminal position tolerance at S4
p2.max_terminal_refines = 4;         % extra S4 targeting attempts if nonlinear drift remains
p2.tof_terminal_refine = 180;        % [s] time per final retargeting leg
p2.Isp_fallback_s = 220;             % [s] used only if Mission_Config has no Isp field

% Current actual relative state after Phase 1
[rel0_lvlh, vrel0_lvlh] = rel_state_lvlh_local(X_chaser, X_target);
fprintf('   Phase 2 initial LVLH rel-pos = [%+.2f, %+.2f, %+.2f] m\n', ...
        rel0_lvlh(1), rel0_lvlh(2), rel0_lvlh(3));
fprintf('   Phase 2 initial LVLH rel-vel = [%+.4f, %+.4f, %+.4f] m/s\n', ...
        vrel0_lvlh(1), vrel0_lvlh(2), vrel0_lvlh(3));

% Initialize Phase 2 history containers
hist_pos = rel0_lvlh;
hist_mass = X_chaser(14);
hist_p2 = struct();
hist_p2.pos = X_chaser(1:3);
hist_p2.time = 0;
hist_p2.mass = X_chaser(14);
phase2_time = 0;
dV_p2 = 0;
fuel_p2 = 0;

% Keep a list of meaningful Phase 2 points for plotting.
phase2_targets = [];
phase2_target_times = [];      % [s] elapsed time from Phase 2 start
phase2_tofs = [];
phase2_names = strings(1,0);

% -------------------------------------------------------------------------
% 2-0. Optional cleanup to S2, then brake to make S2 a true hold point.
% -------------------------------------------------------------------------
if norm(rel0_lvlh - p2.S2) > p2.initial_S2_tol
    tof_seg = p2.tof_initial_s2;
    [r_rel, v_rel] = rel_state_lvlh_local(X_chaser, X_target);
    n_now = target_mean_motion_local(X_target);
    dv_lvlh = cw_delta_v_to_waypoint_local(r_rel, v_rel, p2.S2, tof_seg, n_now);

    [X_chaser, fuel_seg] = apply_impulse_lvlh_local(X_chaser, X_target, dv_lvlh, sys, p2);
    dV_p2 = dV_p2 + norm(dv_lvlh);
    fuel_p2 = fuel_p2 + fuel_seg;

    fprintf('   cleanup_to_S2     : target [%+7.1f,%+7.1f,%+6.1f] m, TOF %5.0f s, dV %8.4f m/s\n', ...
            p2.S2(1), p2.S2(2), p2.S2(3), tof_seg, norm(dv_lvlh));

    [X_chaser, X_target, seg_hist] = propagate_pair_free_local(X_chaser, X_target, tof_seg, p2.dt, sys, phase2_time);
    phase2_time = seg_hist.time(end);

    [hist_pos, hist_mass, hist_p2] = append_phase2_segment_local(hist_pos, hist_mass, hist_p2, seg_hist);
end

% S2 hold trim: cancel any remaining LVLH relative velocity before the
% cycloidal free drift. This is necessary because the 4*v0/n relation assumes
% a clean S2 starting condition except for the deliberate -V-bar impulse.
[r_s2, v_s2] = rel_state_lvlh_local(X_chaser, X_target);
dv_hold_s2_lvlh = -v_s2;
if norm(dv_hold_s2_lvlh) > 1e-6
    [X_chaser, fuel_seg] = apply_impulse_lvlh_local(X_chaser, X_target, dv_hold_s2_lvlh, sys, p2);
    dV_p2 = dV_p2 + norm(dv_hold_s2_lvlh);
    fuel_p2 = fuel_p2 + fuel_seg;
    hist_mass(end) = X_chaser(14);
    hist_p2.mass(end) = X_chaser(14);
    fprintf('   S2_hold_trim      : residual rel-vel canceled, dV %8.4f m/s\n', norm(dv_hold_s2_lvlh));
end

% Record S2 waypoint time after optional cleanup and hold trim.
[phase2_targets, phase2_target_times, phase2_tofs, phase2_names] = ...
    append_phase2_waypoint_local(phase2_targets, phase2_target_times, phase2_tofs, phase2_names, p2.S2, phase2_time, "S2", []);

% -------------------------------------------------------------------------
% 2-1. S2 -> S3 natural cycloidal drift using one -V-bar impulse.
% -------------------------------------------------------------------------
n_now = target_mean_motion_local(X_target);
v0_cycloid = n_now * p2.delta_R_cycloid / 4;
dv_cycloid_lvlh = [0; p2.vbar_burn_sign * v0_cycloid; 0];
expected_delta_R_code = 4 * dv_cycloid_lvlh(2) / n_now;

[X_chaser, fuel_seg] = apply_impulse_lvlh_local(X_chaser, X_target, dv_cycloid_lvlh, sys, p2);
dV_p2 = dV_p2 + norm(dv_cycloid_lvlh);
fuel_p2 = fuel_p2 + fuel_seg;
hist_mass(end) = X_chaser(14);
hist_p2.mass(end) = X_chaser(14);

fprintf('   S2_to_S3_cycloid  : single %+.4f m/s V-bar impulse, |delta_R|max %.1f m', ...
        dv_cycloid_lvlh(2), p2.delta_R_cycloid);
fprintf(' (current LVLH signed delta_R %.1f m)\n', expected_delta_R_code);

% Propagate freely until the chaser first reaches the target R-bar line,
% i.e., until V-bar coordinate crosses zero.
max_cycloid_time = p2.max_cycloid_orbits * 2*pi / n_now;
cycloid_elapsed = 0;
[r_prev, ~] = rel_state_lvlh_local(X_chaser, X_target);
vbar_prev = r_prev(2);
initial_vbar_sign = sign(vbar_prev);
if initial_vbar_sign == 0
    initial_vbar_sign = -1;
end
crossed_rbar = false;

while cycloid_elapsed < max_cycloid_time
    [X_chaser, X_target, seg_hist] = propagate_pair_free_local(X_chaser, X_target, p2.dt, p2.dt, sys, phase2_time);
    phase2_time = seg_hist.time(end);
    cycloid_elapsed = cycloid_elapsed + p2.dt;

    [hist_pos, hist_mass, hist_p2] = append_phase2_segment_local(hist_pos, hist_mass, hist_p2, seg_hist);

    [r_now, v_now] = rel_state_lvlh_local(X_chaser, X_target);
    vbar_now = r_now(2);

    if abs(vbar_now) <= p2.vbar_cross_tol || sign(vbar_now) ~= initial_vbar_sign
        crossed_rbar = true;
        break;
    end
    vbar_prev = vbar_now;
end

if ~crossed_rbar
    error('Phase 2 cycloidal drift did not reach the R-bar line within %.2f orbits. Check S2 offset, delta_R_cycloid, and sign convention.', p2.max_cycloid_orbits);
end

[r_s3, v_s3] = rel_state_lvlh_local(X_chaser, X_target);
p2.S3 = [r_s3(1); 0; 0];
[phase2_targets, phase2_target_times, phase2_tofs, phase2_names] = ...
    append_phase2_waypoint_local(phase2_targets, phase2_target_times, phase2_tofs, phase2_names, p2.S3, phase2_time, "S3", cycloid_elapsed);

fprintf('      S3 detected at first V-bar crossing after %.2f min\n', cycloid_elapsed/60);
fprintf('      S3 actual LVLH rel-pos = [%+.3f, %+.3f, %+.3f] m\n', r_s3(1), r_s3(2), r_s3(3));
fprintf('      S3 actual LVLH rel-vel = [%+.5f, %+.5f, %+.5f] m/s\n', v_s3(1), v_s3(2), v_s3(3));

% Brake at S3 before starting the controlled R-bar hop sequence. Without this,
% the next S3->S4 hop starts with a large natural-drift velocity and can become
% an unsafe fly-by rather than an approach.
dv_hold_s3_lvlh = -v_s3;
if norm(dv_hold_s3_lvlh) > 1e-6
    [X_chaser, fuel_seg] = apply_impulse_lvlh_local(X_chaser, X_target, dv_hold_s3_lvlh, sys, p2);
    dV_p2 = dV_p2 + norm(dv_hold_s3_lvlh);
    fuel_p2 = fuel_p2 + fuel_seg;
    hist_mass(end) = X_chaser(14);
    hist_p2.mass(end) = X_chaser(14);
    fprintf('   S3_hold_brake     : cycloid rel-vel canceled, dV %8.4f m/s\n', norm(dv_hold_s3_lvlh));
end

% -------------------------------------------------------------------------
% 2-2. S3 -> S4 R-bar approach.
% -------------------------------------------------------------------------
% Use the same signed R-bar side as the actual S3. This avoids commanding the
% chaser to cross through the target just because of a sign-convention mismatch.
approach_R_sign = sign(p2.S3(1));
if approach_R_sign == 0
    approach_R_sign = sign(expected_delta_R_code);
end
if approach_R_sign == 0
    approach_R_sign = 1;
end
p2.S4 = [approach_R_sign * p2.S4_R_abs; 0; 0];

if abs(p2.S3(1)) <= abs(p2.S4(1))
    warning('S3 radial distance %.2f m is already inside or near S4 %.2f m. Skipping R-bar hops and using terminal refine only.', p2.S3(1), p2.S4(1));
    rbar_hops = p2.S4(1);
else
    rbar_hops = linspace(p2.S3(1), p2.S4(1), p2.rbar_hop_count + 1);
    rbar_hops = rbar_hops(2:end);
end

for ii = 1:numel(rbar_hops)
    r_goal = [rbar_hops(ii); 0; 0];
    tof_seg = p2.tof_hop;

    [r_rel, v_rel] = rel_state_lvlh_local(X_chaser, X_target);
    n_now = target_mean_motion_local(X_target);
    dv_lvlh = cw_delta_v_to_waypoint_local(r_rel, v_rel, r_goal, tof_seg, n_now);

    [X_chaser, fuel_seg] = apply_impulse_lvlh_local(X_chaser, X_target, dv_lvlh, sys, p2);
    dV_p2 = dV_p2 + norm(dv_lvlh);
    fuel_p2 = fuel_p2 + fuel_seg;

    fprintf('   Rbar_hop_%02d      : target [%+7.1f,%+7.1f,%+6.1f] m, TOF %5.0f s, depart dV %8.4f m/s\n', ...
            ii, r_goal(1), r_goal(2), r_goal(3), tof_seg, norm(dv_lvlh));

    [X_chaser, X_target, seg_hist] = propagate_pair_free_local(X_chaser, X_target, tof_seg, p2.dt, sys, phase2_time);
    phase2_time = seg_hist.time(end);

    [hist_pos, hist_mass, hist_p2] = append_phase2_segment_local(hist_pos, hist_mass, hist_p2, seg_hist);

    [r_arrive, v_arrive] = rel_state_lvlh_local(X_chaser, X_target);

    % Make each hop a real hold point by braking the residual relative velocity.
    % This is more physical/safe than only doing one final brake at S4.
    dv_brake_lvlh = -v_arrive;
    [X_chaser, fuel_brake] = apply_impulse_lvlh_local(X_chaser, X_target, dv_brake_lvlh, sys, p2);
    dV_p2 = dV_p2 + norm(dv_brake_lvlh);
    fuel_p2 = fuel_p2 + fuel_brake;
    hist_mass(end) = X_chaser(14);
    hist_p2.mass(end) = X_chaser(14);

    if ii == numel(rbar_hops)
        waypoint_name = "S4";
    else
        waypoint_name = "WP" + string(ii);
    end
    [phase2_targets, phase2_target_times, phase2_tofs, phase2_names] = ...
        append_phase2_waypoint_local(phase2_targets, phase2_target_times, phase2_tofs, phase2_names, r_goal, phase2_time, waypoint_name, tof_seg);

    [r_hold, v_hold] = rel_state_lvlh_local(X_chaser, X_target);
    fprintf('      arrival error: pos %.3f m, brake dV %.4f m/s, post-brake rel-vel %.5f m/s\n', ...
            norm(r_hold - r_goal), norm(dv_brake_lvlh), norm(v_hold));
end

% Nonlinear/J2 residual cleanup at S4. This is still done by impulses and
% free propagation, not by overwriting the state.
for refine = 1:p2.max_terminal_refines
    [r_rel, v_rel] = rel_state_lvlh_local(X_chaser, X_target);
    pos_err = norm(r_rel - p2.S4);
    if pos_err <= p2.capture_pos_tol
        break;
    end

    n_now = target_mean_motion_local(X_target);
    dv_lvlh = cw_delta_v_to_waypoint_local(r_rel, v_rel, p2.S4, p2.tof_terminal_refine, n_now);
    [X_chaser, fuel_seg] = apply_impulse_lvlh_local(X_chaser, X_target, dv_lvlh, sys, p2);
    dV_p2 = dV_p2 + norm(dv_lvlh);
    fuel_p2 = fuel_p2 + fuel_seg;

    fprintf('   terminal_refine_%d : remaining pos %.3f m, TOF %5.0f s, dV %8.4f m/s\n', ...
            refine, pos_err, p2.tof_terminal_refine, norm(dv_lvlh));

    [X_chaser, X_target, seg_hist] = propagate_pair_free_local(X_chaser, X_target, p2.tof_terminal_refine, p2.dt, sys, phase2_time);
    phase2_time = seg_hist.time(end);

    [hist_pos, hist_mass, hist_p2] = append_phase2_segment_local(hist_pos, hist_mass, hist_p2, seg_hist);
end

% Final braking impulse: cancel residual LVLH relative velocity at S4.
[~, v_final] = rel_state_lvlh_local(X_chaser, X_target);
dv_stop_lvlh = -v_final;
[X_chaser, fuel_stop] = apply_impulse_lvlh_local(X_chaser, X_target, dv_stop_lvlh, sys, p2);
dV_p2 = dV_p2 + norm(dv_stop_lvlh);
fuel_p2 = fuel_p2 + fuel_stop;
hist_mass(end) = X_chaser(14);
hist_p2.mass(end) = X_chaser(14);

[r_final, v_final] = rel_state_lvlh_local(X_chaser, X_target);
fprintf('   terminal braking dV: %.4f m/s\n', norm(dv_stop_lvlh));
fprintf('   Phase 2 final LVLH rel-pos = [%+.3f, %+.3f, %+.3f] m\n', r_final(1), r_final(2), r_final(3));
fprintf('   Phase 2 final LVLH rel-vel = [%+.5f, %+.5f, %+.5f] m/s\n', v_final(1), v_final(2), v_final(3));
fprintf('   Phase 2 total dV: %.4f m/s, fuel: %.4f kg, elapsed: %.2f min\n', dV_p2, fuel_p2, phase2_time/60);

m_current = X_chaser(14);
Budget = [Budget; {"Phase 2: Cycloid + R-bar", dV_p2, fuel_p2, m_current}];

%% 4. Phase 3: Re-entry
fprintf('\n[Phase 3] 3-DOF re-entry simulation start...\n');

% Select Phase 3 mode here.
%   "HOHMANN"        : legacy direct FPA-targeted Hohmann-style descent.
%   "R_BAR_200_FPA" : lower to 200 km, wait until below the target on R-bar,
%                     then inject toward the 120 km / 4 deg FPA interface.
reentry_mode = "R_BAR_200_FPA";
reentry_mode_env = getenv('RENDEZVOUS_PHASE3_MODE');
if strlength(reentry_mode_env) > 0
    reentry_mode = string(reentry_mode_env);
end
fprintf('   selected Phase 3 mode: %s\n', reentry_mode);

% Set true to charge propellant for the final 200 km -> 120 km injection in
% R_BAR_200_FPA mode. The default keeps this injection fuel-excluded.
charge_final_reentry_fuel = false;
charge_final_reentry_fuel_env = getenv('RENDEZVOUS_CHARGE_FINAL_REENTRY_FUEL');
if strlength(charge_final_reentry_fuel_env) > 0
    charge_final_reentry_fuel = parse_bool_setting_local(charge_final_reentry_fuel_env);
end
custom_params.charge_final_reentry_fuel = charge_final_reentry_fuel;
fprintf('   charge final 200 km -> 120 km injection fuel: %s\n', bool_label_local(charge_final_reentry_fuel));

X_orbiting_chaser_entry_relay0 = X_chaser;

if reentry_mode == "HOHMANN"
    [X_chaser, X_target, dV_p3, fuel_p3, hist_p3, reentry_info] = ...
        run_phase3_hohmann_fpa_local(sys, X_chaser, X_target, custom_params);

    fprintf('   final altitude: %.2f km\n', (norm(X_chaser(1:3)) - sys.Re)/1000);

elseif reentry_mode == "R_BAR_200_FPA"
    [X_chaser, X_target, dV_p3, fuel_p3, hist_p3, reentry_info] = ...
        run_phase3_rbar_200_fpa_local(sys, X_chaser, X_target, custom_params);

    fprintf('   final altitude: %.2f km\n', (norm(X_chaser(1:3)) - sys.Re)/1000);
    if reentry_info.final_injection_fuel_charged
        fprintf('   final 200 km -> 120 km injection dV %.4f m/s and fuel %.4f kg are included in Phase 3 budget.\n', ...
                reentry_info.final_injection_dV, reentry_info.final_injection_fuel);
    else
        fprintf('   final 200 km -> 120 km injection dV %.4f m/s is included in Phase 3 dV, but its fuel is excluded.\n', ...
                reentry_info.final_injection_dV);
    end

else
    error('Unknown Phase 3 reentry_mode: %s. Use "HOHMANN" or "R_BAR_200_FPA".', reentry_mode);
end

m_current = X_chaser(14);
Budget = [Budget; {"Phase 3: "+reentry_mode, dV_p3, fuel_p3, m_current}];

[X_entry_interface, entry_interface_info] = entry_interface_state_from_hist_local(hist_p3, X_chaser, sys, 120e3);
phase3_elapsed_to_interface = entry_interface_info.time_s;
fprintf('   selected entry interface: altitude %.3f km, FPA %.3f deg, time %.2f s after Phase 3 start\n', ...
        entry_interface_info.altitude_m/1000, entry_interface_info.fpa_deg, entry_interface_info.time_s);

fprintf('\n[Phase 4] Atmospheric re-entry from 120 km interface...\n');
entry_params = struct();
entry_params.shape_name = sys.reentry_vehicle.selected_shape;
[X_reentry_vehicle, ~, hist_reentry, reentry_atmo_info] = ...
    Reentry_Propagator(sys, X_entry_interface, X_orbiting_chaser_entry_relay0, phase3_elapsed_to_interface, entry_params);

Budget = [Budget; {"Phase 4: Atmospheric Entry", 0, 0, X_reentry_vehicle(14)}];

fprintf('   shape: %s\n', char(reentry_atmo_info.shape_name));
fprintf('   entry duration: %.2f s, final altitude: %.2f km\n', ...
        reentry_atmo_info.duration_s, reentry_atmo_info.final_altitude_m/1000);
fprintf('   max heat flux: %.3f W/cm^2, total heat load: %.3f MJ/m^2\n', ...
        reentry_atmo_info.max_heat_flux_W_m2/1e4, reentry_atmo_info.total_heat_load_J_m2/1e6);
fprintf('   max dynamic pressure: %.3f kPa, max aero g-load: %.3f g\n', ...
        reentry_atmo_info.max_dynamic_pressure_Pa/1e3, reentry_atmo_info.max_g_load);
fprintf('   LOS maintained: %s, min Earth-limb clearance: %.2f km, min elevation: %.2f deg\n', ...
        char(bool_label_local(reentry_atmo_info.los_maintained)), ...
        reentry_atmo_info.min_los_clearance_m/1000, reentry_atmo_info.min_los_elevation_deg);
if ~reentry_atmo_info.los_maintained
    fprintf('   first LOS loss after entry interface: %.2f s\n', reentry_atmo_info.first_los_loss_time_s);
end

%% 5. Summary and Output
disp(' ');
disp('=== Final Mission Delta-V & Mass Budget ===');
disp(Budget);
fprintf('Total Delta-V required: %.2f m/s\n', sum(Budget.DeltaV_ms));
fprintf('Total Fuel consumed:    %.2f kg\n', sum(Budget.Fuel_Consumed_kg));
fprintf('Remaining mass:         %.2f kg\n', X_reentry_vehicle(14));

% Plotting R-bar trajectory
figure('Name','Proximity Operations','Color','w');
plot(hist_pos(2,:), hist_pos(1,:), 'b-', 'LineWidth', 2); hold on;
plot(phase2_targets(2,:), phase2_targets(1,:), 'ko', 'MarkerSize', 5, 'MarkerFaceColor', 'w');
plot(0,0,'r^','MarkerSize',10,'MarkerFaceColor','r');

% Waypoint time labels
for kk = 1:size(phase2_targets, 2)
    x_wp = phase2_targets(2, kk);   % V-bar
    y_wp = phase2_targets(1, kk);   % R-bar

    label_txt = sprintf('%s, %.1f min', ...
        char(phase2_names(kk)), phase2_target_times(kk)/60);

    text(x_wp, y_wp, ['  ' label_txt], ...
        'FontSize', 8, ...
        'VerticalAlignment', 'bottom', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', 'w', ...
        'Margin', 1);
end

grid on;
xlabel('V-bar (m)');
ylabel('R-bar (m)');
title('R-bar Approach Trajectory (LVLH)');
legend('Chaser Trajectory', 'Commanded Waypoints', 'Target', 'Location', 'best');
set(gca, 'XDir', 'reverse'); % Flight direction to the left

%% 6. Mission Profile Visualization
fprintf('\nGenerating visualization dashboard...\n');

figure('Name', 'Mission Comprehensive Dashboard', 'Color', 'w', 'Position', [100, 100, 1400, 800]);

% --- (1) 3D Mission Trajectory (ECI Frame) ---
subplot(2, 2, [1, 3]);
% Earth reference sphere.
[XE, YE, ZE] = sphere(50);
surf(XE*sys.Re/1e3, YE*sys.Re/1e3, ZE*sys.Re/1e3, 'FaceColor', [0.2 0.5 0.8], 'EdgeColor', 'none', 'FaceAlpha', 0.6);
hold on; grid on; axis equal;

% Trajectories in km.
plot3(hist_p1.pos(1,:)/1e3, hist_p1.pos(2,:)/1e3, hist_p1.pos(3,:)/1e3, 'g-', 'LineWidth', 1.5); % Phase 1
plot3(hist_p2.pos(1,:)/1e3, hist_p2.pos(2,:)/1e3, hist_p2.pos(3,:)/1e3, 'b-', 'LineWidth', 1.5); % Phase 2
plot3(hist_p3.pos(1,:)/1e3, hist_p3.pos(2,:)/1e3, hist_p3.pos(3,:)/1e3, 'r-', 'LineWidth', 1.5); % Phase 3
plot3(hist_reentry.rv_pos(1,:)/1e3, hist_reentry.rv_pos(2,:)/1e3, hist_reentry.rv_pos(3,:)/1e3, 'm-', 'LineWidth', 1.5);
plot3(hist_reentry.chaser_pos(1,:)/1e3, hist_reentry.chaser_pos(2,:)/1e3, hist_reentry.chaser_pos(3,:)/1e3, 'c--', 'LineWidth', 1.0);

% Target-orbit reference line.
theta = linspace(0, 2*pi, 100);
plot3((sys.Re+sys.h_target)/1e3*cos(theta), zeros(1,100), (sys.Re+sys.h_target)/1e3*sin(theta), 'k--', 'LineWidth', 1);

title('3D Mission Trajectory (Earth Centered Inertial)');
xlabel('X (km)'); ylabel('Y (km)'); zlabel('Z (km)');
legend('Earth', 'Phase 1: Phasing (Ascent)', 'Phase 2: +R-bar Prox Ops', ...
       'Phase 3: De-orbit to 120km', 'Phase 4: Atmospheric Entry RV', ...
       'Orbiting Chaser / Relay', 'Target Orbit (500km)', 'Location', 'best');
view(45, 30);

% --- (2) Altitude vs Time Profile ---
subplot(2, 2, 2);
alt_p1 = vecnorm(hist_p1.pos) - sys.Re;
alt_p2 = vecnorm(hist_p2.pos) - sys.Re;
alt_p3 = vecnorm(hist_p3.pos) - sys.Re;
time_p1 = hist_p1.time / 3600;
time_p2 = hist_p2.time / 3600;
time_p3 = hist_p3.time / 3600;
time_reentry = hist_reentry.time / 3600;
entry_time_offset = time_p1(end) + time_p2(end) + time_p3(end);

plot(time_p1, alt_p1/1e3, 'g-', 'LineWidth', 2); hold on;
plot(time_p2 + time_p1(end), alt_p2/1e3, 'b-', 'LineWidth', 2);
% Continue Phase 3/4 time axes after Phase 1/2.
plot(time_p3 + time_p1(end) + time_p2(end), alt_p3/1e3, 'r-', 'LineWidth', 2);
plot(time_reentry + entry_time_offset, hist_reentry.altitude/1e3, 'm-', 'LineWidth', 2);
yline(sys.h_insert/1e3, 'k:', 'Insertion (300km)');
yline(sys.h_target/1e3, 'k--', 'Target (500km)');
yline(sys.h_reentry/1e3, 'k:', 'Re-entry (200km)');
yline(120, 'm:', 'Entry Interface (120km)');
yline(sys.reentry_vehicle.terminal_altitude/1e3, 'm--', 'Entry Stop');

title('Altitude Profile');
xlabel('Mission Time (Hours)'); ylabel('Altitude (km)');
legend('Phasing Maneuver', '+R-bar Prox Ops', 'De-orbit to 120km', 'Atmospheric Entry');
grid on;

% --- (3) Mass Depletion Profile ---
subplot(2, 2, 4);
plot(time_p1, hist_p1.mass, 'g-', 'LineWidth', 2); hold on;
plot(time_p2 + time_p1(end), hist_p2.mass, 'b-', 'LineWidth', 2);
plot(time_p3 + time_p1(end) + time_p2(end), hist_p3.mass, 'r-', 'LineWidth', 2);
plot(time_reentry + entry_time_offset, hist_reentry.mass, 'm-', 'LineWidth', 2);

title('Spacecraft Mass Depletion (Fuel Consumption)');
xlabel('Mission Time (Hours)'); ylabel('Mass (kg)');
legend('Fuel used in Phasing', 'Fuel used in Prox Ops', 'Fuel used in De-orbit', 'Atmospheric Entry RV');
grid on;

figure('Name', 'Atmospheric Re-entry Diagnostics', 'Color', 'w', 'Position', [150, 120, 1300, 820]);
entry_min = hist_reentry.time / 60;

subplot(3, 2, 1);
plot(entry_min, hist_reentry.altitude/1e3, 'm-', 'LineWidth', 2); grid on;
xlabel('Entry Time (min)'); ylabel('Altitude (km)');
title('Re-entry Altitude');

subplot(3, 2, 2);
plot(entry_min, hist_reentry.speed_rel/1e3, 'k-', 'LineWidth', 2); grid on;
xlabel('Entry Time (min)'); ylabel('Relative Speed (km/s)');
title('Atmosphere-relative Speed');

subplot(3, 2, 3);
plot(entry_min, hist_reentry.dynamic_pressure/1e3, 'b-', 'LineWidth', 2); grid on;
xlabel('Entry Time (min)'); ylabel('q (kPa)');
title('Dynamic Pressure');

subplot(3, 2, 4);
plot(entry_min, hist_reentry.heat_flux/1e4, 'r-', 'LineWidth', 2); grid on;
xlabel('Entry Time (min)'); ylabel('Heat Flux (W/cm^2)');
title('Sutton-Graves Stagnation Heat Flux');

subplot(3, 2, 5);
plot(entry_min, hist_reentry.g_load, 'Color', [0.2 0.5 0.2], 'LineWidth', 2); grid on;
xlabel('Entry Time (min)'); ylabel('Aero Accel (g)');
title('Aerodynamic g-load');

subplot(3, 2, 6);
yyaxis left;
plot(entry_min, hist_reentry.los_clearance/1e3, 'c-', 'LineWidth', 2); grid on;
ylabel('Earth-limb Clearance (km)');
yyaxis right;
plot(entry_min, hist_reentry.los_elevation_deg, 'Color', [0.4 0.2 0.8], 'LineWidth', 2);
ylabel('RV-to-Chaser Elevation (deg)');
xlabel('Entry Time (min)');
title('Chaser-RV Line of Sight');

%% Local helper functions for entry-interface handoff
function [X_entry, info] = entry_interface_state_from_hist_local(hist, X_fallback, sys, target_altitude)
    X_entry = X_fallback;
    info = struct('time_s', 0, 'altitude_m', norm(X_fallback(1:3)) - sys.Re, 'fpa_deg', NaN);

    if ~isfield(hist, 'pos') || isempty(hist.pos) || ~isfield(hist, 'vel') || isempty(hist.vel)
        info.fpa_deg = flight_path_angle_deg_local(X_entry(1:3), X_entry(4:6));
        return;
    end

    alt = vecnorm(hist.pos, 2, 1) - sys.Re;
    idx_cross = find(alt(1:end-1) >= target_altitude & alt(2:end) <= target_altitude, 1, 'first');

    if ~isempty(idx_cross)
        i0 = idx_cross;
        i1 = idx_cross + 1;
        denom = alt(i1) - alt(i0);
        if abs(denom) <= eps
            alpha = 0;
        else
            alpha = (target_altitude - alt(i0)) / denom;
        end
        alpha = min(1, max(0, alpha));

        r_entry = hist.pos(:,i0) + alpha * (hist.pos(:,i1) - hist.pos(:,i0));
        v_entry = hist.vel(:,i0) + alpha * (hist.vel(:,i1) - hist.vel(:,i0));
        if isfield(hist, 'mass') && numel(hist.mass) >= i1
            mass_entry = hist.mass(i0) + alpha * (hist.mass(i1) - hist.mass(i0));
        else
            mass_entry = X_fallback(14);
        end
        if isfield(hist, 'time') && numel(hist.time) >= i1
            time_entry = hist.time(i0) + alpha * (hist.time(i1) - hist.time(i0));
        else
            time_entry = 0;
        end
    else
        [~, idx] = min(abs(alt - target_altitude));
        r_entry = hist.pos(:,idx);
        v_entry = hist.vel(:,idx);
        if isfield(hist, 'mass') && numel(hist.mass) >= idx
            mass_entry = hist.mass(idx);
        else
            mass_entry = X_fallback(14);
        end
        if isfield(hist, 'time') && numel(hist.time) >= idx
            time_entry = hist.time(idx);
        else
            time_entry = 0;
        end
    end

    X_entry = zeros(14,1);
    X_entry(1:6) = [r_entry; v_entry];
    X_entry(7:10) = [0;0;0;1];
    X_entry(11:13) = [0;0;0];
    X_entry(14) = mass_entry;

    info.time_s = time_entry;
    info.altitude_m = norm(r_entry) - sys.Re;
    info.fpa_deg = flight_path_angle_deg_local(r_entry, v_entry);
end

function fpa_deg = flight_path_angle_deg_local(r, v)
    rhat = r / norm(r);
    v_radial = dot(v, rhat);
    v_horizontal = norm(v - v_radial * rhat);
    fpa_deg = rad2deg(atan2(v_radial, v_horizontal));
end

%% Local helper functions for JSON mission configuration
function cfg = load_mission_json_config_local()
    cfg = struct();

    config_path = strtrim(string(getenv('RENDEZVOUS_CONFIG_JSON')));
    if strlength(config_path) == 0
        config_path = strtrim(string(getenv('RENDEZVOUS_CONFIG')));
    end

    if strlength(config_path) == 0
        return;
    end

    if ~isfile(config_path)
        error('Mission JSON config not found: %s', char(config_path));
    end

    cfg = jsondecode(fileread(config_path));
    fprintf('Loaded mission JSON config: %s\n', char(config_path));
end

function sys = apply_json_to_sys_local(sys, cfg)
    if isempty(fieldnames(cfg))
        return;
    end

    sys.h_insert = get_json_number_local(cfg, {'scenario','h_chaser_km'}, sys.h_insert/1e3) * 1e3;
    sys.h_target = get_json_number_local(cfg, {'scenario','h_target_km'}, sys.h_target/1e3) * 1e3;
    sys.h_wait = get_json_number_local(cfg, {'scenario','h_wait_km'}, sys.h_wait/1e3) * 1e3;

    sys.Chaser_Mass_Init = get_json_number_local(cfg, {'maneuver','initial_mass_kg'}, sys.Chaser_Mass_Init);

    sys.maneuver.default_burn_model = get_json_string_local(cfg, {'phase1','burn_model'}, sys.maneuver.default_burn_model);
    sys.maneuver.finite_burn_thrust = get_json_number_local(cfg, {'maneuver','finite_burn_thrust_N'}, sys.maneuver.finite_burn_thrust);
    sys.maneuver.finite_burn_isp = get_json_number_local(cfg, {'maneuver','finite_burn_isp_s'}, sys.maneuver.finite_burn_isp);
    sys.maneuver.finite_burn_dt = get_json_number_local(cfg, {'maneuver','finite_burn_dt_s'}, sys.maneuver.finite_burn_dt);
    sys.maneuver.max_single_burn_duration = get_json_number_local(cfg, {'maneuver','max_single_burn_duration_s'}, sys.maneuver.max_single_burn_duration);
    sys.maneuver.max_single_burn_delta_v = get_json_number_local(cfg, {'maneuver','max_single_burn_delta_v_m_s'}, sys.maneuver.max_single_burn_delta_v);

    if has_json_path_local(cfg, {'environment','atmospheric_drag'})
        sys.environment.atmospheric_drag.enabled = get_json_bool_local(cfg, {'environment','atmospheric_drag','enabled'}, sys.environment.atmospheric_drag.enabled);
        sys.environment.atmospheric_drag.model = get_json_string_local(cfg, {'environment','atmospheric_drag','model'}, sys.environment.atmospheric_drag.model);
        sys.environment.atmospheric_drag.use_matlab_atmosisa = get_json_bool_local(cfg, {'environment','atmospheric_drag','use_matlab_atmosisa'}, sys.environment.atmospheric_drag.use_matlab_atmosisa);
        sys.environment.atmospheric_drag.co_rotate_atmosphere = get_json_bool_local(cfg, {'environment','atmospheric_drag','co_rotate_atmosphere'}, sys.environment.atmospheric_drag.co_rotate_atmosphere);
        sys.environment.atmospheric_drag.earth_rotation_rad_s = get_json_number_local(cfg, {'environment','atmospheric_drag','earth_rotation_rad_s'}, sys.environment.atmospheric_drag.earth_rotation_rad_s);
        sys.environment.atmospheric_drag.chaser_cd = get_json_number_local(cfg, {'environment','atmospheric_drag','chaser_cd'}, sys.environment.atmospheric_drag.chaser_cd);
        sys.environment.atmospheric_drag.chaser_area_m2 = get_json_number_local(cfg, {'environment','atmospheric_drag','chaser_area_m2'}, sys.environment.atmospheric_drag.chaser_area_m2);
        sys.environment.atmospheric_drag.target_cd = get_json_number_local(cfg, {'environment','atmospheric_drag','target_cd'}, sys.environment.atmospheric_drag.target_cd);
        sys.environment.atmospheric_drag.target_area_m2 = get_json_number_local(cfg, {'environment','atmospheric_drag','target_area_m2'}, sys.environment.atmospheric_drag.target_area_m2);
        sys.Target_Mass = get_json_number_local(cfg, {'environment','atmospheric_drag','target_mass_kg'}, sys.Target_Mass);
    end

    if has_json_path_local(cfg, {'reentry'})
        sys.reentry_vehicle.selected_shape = get_json_string_local(cfg, {'reentry','shape'}, sys.reentry_vehicle.selected_shape);
        sys.reentry_vehicle.dt = get_json_number_local(cfg, {'reentry','dt_s'}, sys.reentry_vehicle.dt);
        sys.reentry_vehicle.max_time = get_json_number_local(cfg, {'reentry','max_time_s'}, sys.reentry_vehicle.max_time);
        sys.reentry_vehicle.terminal_altitude = get_json_number_local(cfg, {'reentry','terminal_altitude_m'}, sys.reentry_vehicle.terminal_altitude);
        sys.reentry_vehicle.lift_enabled = get_json_bool_local(cfg, {'reentry','lift_enabled'}, sys.reentry_vehicle.lift_enabled);
        if has_json_path_local(cfg, {'reentry','aoa_deg'})
            sys.reentry_vehicle.aoa_deg = get_json_number_local(cfg, {'reentry','aoa_deg'}, 20);
        end
        sys.reentry_vehicle.bank_angle_deg = get_json_number_local(cfg, {'reentry','bank_angle_deg'}, sys.reentry_vehicle.bank_angle_deg);
        sys.reentry_vehicle.los_margin_altitude = get_json_number_local(cfg, {'reentry','los_margin_altitude_m'}, sys.reentry_vehicle.los_margin_altitude);
    end
end

function sys = apply_environment_env_overrides_local(sys)
    drag_model_env = strtrim(string(getenv('RENDEZVOUS_ATMOSPHERIC_DRAG')));
    if strlength(drag_model_env) > 0
        if upper(drag_model_env) == "OFF" || upper(drag_model_env) == "NONE" || upper(drag_model_env) == "0"
            sys.environment.atmospheric_drag.enabled = false;
        else
            sys.environment.atmospheric_drag.enabled = true;
            sys.environment.atmospheric_drag.model = upper(drag_model_env);
        end
    end

    reentry_shape_env = strtrim(string(getenv('RENDEZVOUS_REENTRY_SHAPE')));
    if strlength(reentry_shape_env) > 0
        sys.reentry_vehicle.selected_shape = upper(reentry_shape_env);
    end
end

function print_environment_config_local(sys)
    drag = sys.environment.atmospheric_drag;
    if drag.enabled
        fprintf('Environment: orbital atmospheric drag ON (%s), Cd/A chaser %.2f/%.2f m^2, target %.2f/%.2f m^2\n', ...
                char(string(drag.model)), drag.chaser_cd, drag.chaser_area_m2, drag.target_cd, drag.target_area_m2);
    else
        fprintf('Environment: orbital atmospheric drag OFF\n');
    end
    fprintf('Re-entry vehicle: shape %s, terminal altitude %.1f km, lift model %s, entry atmosphere ISA76\n', ...
            char(string(sys.reentry_vehicle.selected_shape)), sys.reentry_vehicle.terminal_altitude/1000, ...
            char(bool_label_local(sys.reentry_vehicle.lift_enabled)));
end

function [phasing_mode, custom_params] = apply_json_to_phase1_local(phasing_mode, custom_params, cfg)
    if isempty(fieldnames(cfg)) || ~isfield(cfg, 'phase1')
        return;
    end

    phasing_mode = get_json_string_local(cfg, {'phase1','mode'}, phasing_mode);
    custom_params.burn_model = get_json_string_local(cfg, {'phase1','burn_model'}, custom_params.burn_model);

    if has_json_path_local(cfg, {'phase1','phase_angle_deg'})
        custom_params.phase_angle = get_json_number_local(cfg, {'phase1','phase_angle_deg'}, custom_params.phase_angle);
        custom_params.phase_angle_unit = "deg";
    elseif has_json_path_local(cfg, {'phase1','phase_angle_rad'})
        custom_params.phase_angle = get_json_number_local(cfg, {'phase1','phase_angle_rad'}, custom_params.phase_angle);
        custom_params.phase_angle_unit = "rad";
    end

    if has_json_path_local(cfg, {'phase1','gamma_deg'})
        custom_params.gamma = get_json_number_local(cfg, {'phase1','gamma_deg'}, custom_params.gamma);
        custom_params.gamma_unit = "deg";
    elseif has_json_path_local(cfg, {'phase1','gamma_rad'})
        custom_params.gamma = get_json_number_local(cfg, {'phase1','gamma_rad'}, custom_params.gamma);
        custom_params.gamma_unit = "rad";
    end

    custom_params.delta_v = get_json_number_local(cfg, {'phase1','delta_v_m_s'}, custom_params.delta_v);
    custom_params.desired_rel_lvlh = get_json_vector_local(cfg, {'phase1','desired_rel_lvlh_m'}, custom_params.desired_rel_lvlh);

    custom_params.finite_burn_thrust = get_json_number_local(cfg, {'maneuver','finite_burn_thrust_N'}, custom_params.finite_burn_thrust);
    custom_params.finite_burn_isp = get_json_number_local(cfg, {'maneuver','finite_burn_isp_s'}, custom_params.finite_burn_isp);
    custom_params.dt_burn = get_json_number_local(cfg, {'maneuver','finite_burn_dt_s'}, custom_params.dt_burn);
    custom_params.max_single_burn_duration = get_json_number_local(cfg, {'maneuver','max_single_burn_duration_s'}, custom_params.max_single_burn_duration);
    custom_params.max_single_burn_delta_v = get_json_number_local(cfg, {'maneuver','max_single_burn_delta_v_m_s'}, custom_params.max_single_burn_delta_v);

    custom_params.time_step = get_json_number_local(cfg, {'phase1','time_step_s'}, custom_params.time_step);
    custom_params.dt_phase = get_json_number_local(cfg, {'phase1','dt_phase_s'}, custom_params.dt_phase);
    custom_params.dt_capture = get_json_number_local(cfg, {'phase1','dt_capture_s'}, custom_params.dt_capture);
    custom_params.max_wait = get_json_number_local(cfg, {'phase1','max_wait_s'}, custom_params.max_wait);
    custom_params.max_capture_time = get_json_number_local(cfg, {'phase1','max_capture_time_s'}, custom_params.max_capture_time);
    custom_params.capture_pos_tol = get_json_number_local(cfg, {'phase1','capture_pos_tol_m'}, custom_params.capture_pos_tol);
end

function [r, v] = circular_polar_state_local(radius, u_rad, sys)
    r = radius * [cos(u_rad); 0; sin(u_rad)];
    z_over_r = sin(u_rad);
    v_mag = sqrt(sys.mu / radius * (1 - sys.J2 * (sys.Re / radius)^2 * (3*z_over_r^2 - 1)));
    v = v_mag * [-sin(u_rad); 0; cos(u_rad)];
end

function value = get_json_angle_rad_local(cfg, path, default_value)
    value = default_value;
    if has_json_path_local(cfg, path)
        value = deg2rad(get_json_number_local(cfg, path, rad2deg(default_value)));
    end
end

function value = get_json_number_local(cfg, path, default_value)
    value = get_json_value_local(cfg, path, default_value);
    if ischar(value) || isstring(value)
        value = str2double(value);
    end
    if isempty(value) || ~isnumeric(value) || ~isscalar(value) || ~isfinite(value)
        value = default_value;
    end
end

function value = get_json_string_local(cfg, path, default_value)
    value = get_json_value_local(cfg, path, default_value);
    value = string(value);
end

function value = get_json_bool_local(cfg, path, default_value)
    value = get_json_value_local(cfg, path, default_value);
    if islogical(value)
        return;
    end
    if isnumeric(value)
        value = value ~= 0;
        return;
    end
    txt = lower(strtrim(string(value)));
    value = txt == "true" || txt == "1" || txt == "yes" || txt == "on";
end

function value = get_json_vector_local(cfg, path, default_value)
    value = get_json_value_local(cfg, path, default_value);
    value = value(:);
    if numel(value) ~= numel(default_value) || ~isnumeric(value)
        value = default_value;
    end
end

function tf = has_json_path_local(cfg, path)
    tf = true;
    node = cfg;
    for ii = 1:numel(path)
        name = path{ii};
        if ~isstruct(node) || ~isfield(node, name)
            tf = false;
            return;
        end
        node = node.(name);
    end
end

function value = get_json_value_local(cfg, path, default_value)
    if ~has_json_path_local(cfg, path)
        value = default_value;
        return;
    end

    value = cfg;
    for ii = 1:numel(path)
        value = value.(path{ii});
    end
end

%% Local helper functions for Phase 2 waypoint-impulse proximity operations
function [hist_pos, hist_mass, hist_p2] = append_phase2_segment_local(hist_pos, hist_mass, hist_p2, seg_hist)
    hist_pos = [hist_pos, seg_hist.rel];
    hist_mass = [hist_mass, seg_hist.mass];
    hist_p2.pos = [hist_p2.pos, seg_hist.pos];
    hist_p2.time = [hist_p2.time, seg_hist.time];
    hist_p2.mass = [hist_p2.mass, seg_hist.mass];
end

function [targets, target_times, tofs, names] = append_phase2_waypoint_local(targets, target_times, tofs, names, point, time_s, name, tof_s)
    targets = [targets, point];
    target_times = [target_times, time_s];
    names(end+1) = string(name);
    if ~isempty(tof_s)
        tofs = [tofs, tof_s];
    end
end

function [r_rel, v_rel, C_I2L] = rel_state_lvlh_local(X_chaser, X_target)
    r_c = X_chaser(1:3);
    v_c = X_chaser(4:6);
    r_t = X_target(1:3);
    v_t = X_target(4:6);

    h_vec = cross(r_t, v_t);
    i_u = r_t / norm(r_t);          % +R-bar, radial outward
    k_u = h_vec / norm(h_vec);      % +H-bar, orbit normal
    j_u = cross(k_u, i_u);          % +V-bar, along-track
    C_I2L = [i_u'; j_u'; k_u'];

    r_rel = C_I2L * (r_c - r_t);
    w_eci = h_vec / norm(r_t)^2;
    w_lvlh = C_I2L * w_eci;
    v_rel = C_I2L * (v_c - v_t) - cross(w_lvlh, r_rel);
end

function n = target_mean_motion_local(X_target)
    r_t = X_target(1:3);
    v_t = X_target(4:6);
    h_vec = cross(r_t, v_t);
    n = norm(h_vec) / norm(r_t)^2;
end

function dv_lvlh = cw_delta_v_to_waypoint_local(r0, v0, rf, tof, n)
    % CW/Hill single-impulse targeting: choose post-impulse v0+dv so that
    % the linearized relative trajectory reaches rf after tof.
    nt = n * tof;
    s = sin(nt);
    c = cos(nt);

    Phi_rr = [4 - 3*c,        0, 0; ...
              6*(s - nt),     1, 0; ...
              0,              0, c];

    Phi_rv = [s/n,              2*(1-c)/n,       0; ...
              -2*(1-c)/n,      (4*s - 3*nt)/n,  0; ...
              0,               0,               s/n];

    if rcond(Phi_rv) < 1e-10
        error('Phase 2 CW targeting became ill-conditioned. Change the segment TOF away from singular transfer times.');
    end

    v_req = Phi_rv \ (rf - Phi_rr*r0);
    dv_lvlh = v_req - v0;
end

function [X_chaser, fuel_used] = apply_impulse_lvlh_local(X_chaser, X_target, dv_lvlh, sys, p2)
    [~, ~, C_I2L] = rel_state_lvlh_local(X_chaser, X_target);
    dv_eci = C_I2L' * dv_lvlh;
    dv_mag = norm(dv_eci);

    X_chaser(4:6) = X_chaser(4:6) + dv_eci;

    m0 = X_chaser(14);
    Isp = impulse_isp_local(sys, p2);
    g0 = 9.80665;
    if Isp > 0 && dv_mag > 0
        m1 = m0 * exp(-dv_mag/(Isp*g0));
        fuel_used = m0 - m1;
        X_chaser(14) = m1;
    else
        fuel_used = 0;
    end
end

function Isp = impulse_isp_local(sys, p2)
    candidates = {'Isp_Impulsive', 'Isp_RCS', 'Isp_Thruster', 'Isp'};
    Isp = NaN;
    for ii = 1:numel(candidates)
        if isfield(sys, candidates{ii}) && isnumeric(sys.(candidates{ii})) && isscalar(sys.(candidates{ii}))
            Isp = sys.(candidates{ii});
            break;
        end
    end
    if isnan(Isp)
        Isp = p2.Isp_fallback_s;
    end
end

function [X_chaser, X_target, hist] = propagate_pair_free_local(X_chaser, X_target, tof, dt, sys, t0)
    n_steps = ceil(tof/dt);
    hist.rel = zeros(3, n_steps);
    hist.pos = zeros(3, n_steps);
    hist.mass = zeros(1, n_steps);
    hist.time = zeros(1, n_steps);

    t_elapsed = 0;
    for kk = 1:n_steps
        dt_step = min(dt, tof - t_elapsed);
        t_abs = t0 + t_elapsed;

        % Target propagation: 6-DOF wrapper with zero force/torque.
        X_t_state = [X_target; zeros(7,1); sys.Target_Mass];
        k1_t = Env_EOM(t_abs,             X_t_state,               [0;0;0], [0;0;0], sys, false);
        k2_t = Env_EOM(t_abs+dt_step/2,   X_t_state+k1_t*dt_step/2,[0;0;0], [0;0;0], sys, false);
        k3_t = Env_EOM(t_abs+dt_step/2,   X_t_state+k2_t*dt_step/2,[0;0;0], [0;0;0], sys, false);
        k4_t = Env_EOM(t_abs+dt_step,     X_t_state+k3_t*dt_step,  [0;0;0], [0;0;0], sys, false);
        X_target = X_target + (dt_step/6)*(k1_t(1:6) + 2*k2_t(1:6) + 2*k3_t(1:6) + k4_t(1:6));

        % Chaser free-flight propagation after the impulse.
        k1 = Env_EOM(t_abs,             X_chaser,             [0;0;0], [0;0;0], sys, true);
        k2 = Env_EOM(t_abs+dt_step/2,   X_chaser+k1*dt_step/2,[0;0;0], [0;0;0], sys, true);
        k3 = Env_EOM(t_abs+dt_step/2,   X_chaser+k2*dt_step/2,[0;0;0], [0;0;0], sys, true);
        k4 = Env_EOM(t_abs+dt_step,     X_chaser+k3*dt_step,  [0;0;0], [0;0;0], sys, true);
        X_chaser = X_chaser + (dt_step/6)*(k1 + 2*k2 + 2*k3 + k4);

        if norm(X_chaser(7:10)) > 0
            X_chaser(7:10) = X_chaser(7:10) / norm(X_chaser(7:10));
        end

        t_elapsed = t_elapsed + dt_step;
        [r_rel, ~] = rel_state_lvlh_local(X_chaser, X_target);
        hist.rel(:,kk) = r_rel;
        hist.pos(:,kk) = X_chaser(1:3);
        hist.mass(kk) = X_chaser(14);
        hist.time(kk) = t0 + t_elapsed;
    end
end

%% Local helper functions for Phase 3 selectable re-entry modes
function [X_chaser, X_target, dV_used, fuel_used, hist, info] = run_phase3_hohmann_fpa_local(sys, X_chaser, X_target, custom_params)
    dV_used = 0;
    fuel_used = 0;
    hist = init_phase3_hist_local();
    info = struct();

    [target_reentry_r, fpa_calc] = compute_reentry_target_radius_local(norm(X_chaser(1:3)), sys);
    info.fpa_calc = fpa_calc;
    info.reentry_target_radius = target_reentry_r;

    fprintf('   HOHMANN leg: injection toward 120 km / %.2f deg FPA...\n', ...
            rad2deg(sys.reentry_flight_path_angle));
    [X_chaser, dV_entry, fuel_entry] = apply_reentry_departure_impulse_local(X_chaser, target_reentry_r, sys, true);
    dV_used = dV_used + dV_entry;
    fuel_used = fuel_used + fuel_entry;
    info.entry_injection_dV = dV_entry;
    info.entry_injection_fuel = fuel_entry;

    hist = log_phase3_state_local(hist, X_chaser, X_target, 0);

    r_start = norm(X_chaser(1:3));
    a_trans = 0.5 * (r_start + target_reentry_r);
    default_reentry_time = 1.2 * pi * sqrt(a_trans^3 / sys.mu);
    dt_reentry = get_phase3_param_local(custom_params, 'dt_reentry_coast', 2);
    max_reentry_time = get_phase3_param_local(custom_params, 'max_reentry_coast_time', default_reentry_time);

    [X_chaser, X_target, hist_entry, coast_time] = ...
        propagate_until_altitude_local(X_chaser, X_target, sys, 120e3, max_reentry_time, dt_reentry, hist.time_end);
    hist = append_phase3_hist_local(hist, hist_entry);
    info.reentry_coast_time = coast_time;

    fprintf('      120 km interface reached after %.2f min; deorbit fuel charged: %.4f kg.\n', ...
            coast_time/60, fuel_entry);
end

function [X_chaser, X_target, dV_used, fuel_used, hist, info] = run_phase3_rbar_200_fpa_local(sys, X_chaser, X_target, custom_params)
    info = struct();
    hist = init_phase3_hist_local();
    dV_used = 0;
    fuel_used = 0;

    phase3_params = custom_params;
    phase3_params.capture_pos_tol = inf;

    target_200_r = sys.Re + sys.h_reentry;
    fprintf('   R_BAR_200_FPA leg 1: lowering to %.1f km circular parking orbit...\n', sys.h_reentry/1000);
    [X_chaser, dV_drop, fuel_drop, hist_drop, X_target] = ...
        Phasing_Propagator(sys, X_chaser, target_200_r, "HOHMANN", phase3_params, X_target, 3);

    hist = append_phase3_hist_local(hist, hist_drop);
    dV_used = dV_used + dV_drop;
    fuel_used = fuel_used + fuel_drop;

    fprintf('      200 km parking orbit reached: altitude %.2f km, dV %.4f m/s, fuel %.4f kg\n', ...
            (norm(X_chaser(1:3)) - sys.Re)/1000, dV_drop, fuel_drop);

    n_chaser = orbit_rate_from_state_local(X_chaser);
    n_target = orbit_rate_from_state_local(X_target);
    if abs(n_chaser - n_target) > 1e-12
        default_rbar_wait = 2 * 2*pi / abs(n_chaser - n_target);
    else
        default_rbar_wait = 2 * 86400;
    end

    dt_rbar = get_phase3_param_local(custom_params, 'dt_rbar_wait', 30);
    max_rbar_wait = get_phase3_param_local(custom_params, 'max_rbar_wait', default_rbar_wait);
    rbar_vbar_tol = get_phase3_param_local(custom_params, 'rbar_vbar_tol', 10);
    rbar_radial_tol = get_phase3_param_local(custom_params, 'rbar_radial_tol', 50e3);

    fprintf('   R_BAR_200_FPA leg 2: waiting for target R-bar alignment below the station...\n');
    [X_chaser, X_target, hist_wait, wait_time, rel_rbar] = ...
        propagate_until_rbar_below_local(X_chaser, X_target, sys, max_rbar_wait, dt_rbar, rbar_vbar_tol, rbar_radial_tol, hist.time_end);

    hist = append_phase3_hist_local(hist, hist_wait);
    info.rbar_wait_time = wait_time;
    info.rbar_rel_lvlh = rel_rbar;

    fprintf('      R-bar alignment after %.2f min, LVLH rel-pos [%+.1f, %+.1f, %+.1f] m\n', ...
            wait_time/60, rel_rbar(1), rel_rbar(2), rel_rbar(3));

    [target_reentry_r, fpa_calc] = compute_reentry_target_radius_local(norm(X_chaser(1:3)), sys);
    info.fpa_calc = fpa_calc;
    info.reentry_target_radius = target_reentry_r;
    charge_final_fuel = get_phase3_bool_param_local(custom_params, 'charge_final_reentry_fuel', false);

    fprintf('   R_BAR_200_FPA leg 3: injection toward 120 km / %.2f deg FPA (fuel update: %s)...\n', ...
            rad2deg(sys.reentry_flight_path_angle), bool_label_local(charge_final_fuel));
    [X_chaser, dV_entry, fuel_entry] = apply_reentry_departure_impulse_local(X_chaser, target_reentry_r, sys, charge_final_fuel);
    dV_used = dV_used + dV_entry;
    if charge_final_fuel
        fuel_used = fuel_used + fuel_entry;
    end

    info.final_injection_dV = dV_entry;
    info.final_injection_fuel = fuel_entry;
    info.final_injection_fuel_charged = charge_final_fuel;

    hist = log_phase3_state_local(hist, X_chaser, X_target, hist.time_end);

    r_start = norm(X_chaser(1:3));
    a_trans = 0.5 * (r_start + target_reentry_r);
    default_reentry_time = 1.2 * pi * sqrt(a_trans^3 / sys.mu);
    dt_reentry = get_phase3_param_local(custom_params, 'dt_reentry_coast', 2);
    max_reentry_time = get_phase3_param_local(custom_params, 'max_reentry_coast_time', default_reentry_time);

    [X_chaser, X_target, hist_entry, coast_time] = ...
        propagate_until_altitude_local(X_chaser, X_target, sys, 120e3, max_reentry_time, dt_reentry, hist.time_end);

    hist = append_phase3_hist_local(hist, hist_entry);
    info.reentry_coast_time = coast_time;

    if charge_final_fuel
        fprintf('      120 km interface reached after %.2f min; final-injection fuel charged: %.4f kg.\n', ...
                coast_time/60, fuel_entry);
    else
        fprintf('      120 km interface reached after %.2f min; fuel-equivalent %.4f kg was not charged.\n', ...
                coast_time/60, fuel_entry);
    end
end

function [target_r, details] = compute_reentry_target_radius_local(start_r, sys)
    interface_r = sys.Re + 120e3;
    gamma = sys.reentry_flight_path_angle;
    phi = 2 * atan(start_r / (start_r - interface_r) * tan(gamma));
    denom = sin(phi) * cos(gamma) - cos(phi) * sin(gamma);

    if abs(denom) < 1e-12
        error('Re-entry FPA geometry became singular. Check start radius and flight-path angle.');
    end

    ecc = sin(gamma) / denom;
    target_r = (1 - ecc) / (1 + ecc) * start_r;

    if ~isfinite(target_r) || target_r <= 0
        error('Computed invalid re-entry target radius %.6g m.', target_r);
    end

    details = struct();
    details.start_radius = start_r;
    details.interface_radius = interface_r;
    details.flight_path_angle = gamma;
    details.phi = phi;
    details.eccentricity = ecc;
    details.target_radius = target_r;
end

function [X_chaser, dV_mag, fuel_used] = apply_reentry_departure_impulse_local(X_chaser, target_r, sys, charge_fuel)
    r_current = norm(X_chaser(1:3));
    v_current = norm(X_chaser(4:6));
    a_trans = 0.5 * (r_current + target_r);
    sqrt_arg = sys.mu * (2/r_current - 1/a_trans - sys.J2 * sys.Re^2 / r_current^3 * (3 * (X_chaser(3)/r_current)^2 - 1));

    if sqrt_arg <= 0
        error('Computed invalid re-entry injection speed. sqrt argument = %.6g.', sqrt_arg);
    end

    v_trans1 = sqrt(sqrt_arg);
    dV_cmd = v_trans1 - v_current;
    dV_mag = abs(dV_cmd);

    X_chaser(4:6) = X_chaser(4:6) + dV_cmd * X_chaser(4:6) / v_current;

    m0 = X_chaser(14);
    m1 = m0 * exp(-dV_mag / (sys.Isp * sys.g0));
    fuel_used = m0 - m1;
    if charge_fuel
        X_chaser(14) = m1;
    end
end

function [X_chaser, X_target, hist, elapsed, rel_lvlh] = propagate_until_rbar_below_local(X_chaser, X_target, sys, max_wait, dt, vbar_tol, radial_tol, t0)
    hist = init_phase3_hist_local();
    elapsed = 0;
    [rel_prev, ~] = rel_state_lvlh_local(X_chaser, X_target);

    if is_below_target_rbar_local(rel_prev, X_chaser, X_target, radial_tol) && abs(rel_prev(2)) <= vbar_tol
        rel_lvlh = rel_prev;
        hist = log_phase3_state_local(hist, X_chaser, X_target, t0);
        return;
    end

    while elapsed < max_wait - 1e-12
        dt_step = min(dt, max_wait - elapsed);
        X_prev = X_chaser;
        T_prev = X_target;
        y_prev = rel_prev(2);

        [X_next, T_next] = rk4_pair_step_full_local(X_prev, T_prev, dt_step, sys, t0 + elapsed);
        [rel_next, ~] = rel_state_lvlh_local(X_next, T_next);
        y_next = rel_next(2);

        crossed_vbar = (y_prev == 0) || (y_next == 0) || (sign(y_prev) ~= sign(y_next));
        below_target_rbar = is_below_target_rbar_local(rel_next, X_next, T_next, radial_tol);
        if below_target_rbar && (abs(y_next) <= vbar_tol || crossed_vbar)
            if crossed_vbar && y_prev ~= 0 && y_next ~= 0
                [X_chaser, X_target, t_cross] = refine_vbar_crossing_local(X_prev, T_prev, y_prev, dt_step, sys, t0 + elapsed);
                elapsed = elapsed + t_cross;
            else
                X_chaser = X_next;
                X_target = T_next;
                elapsed = elapsed + dt_step;
            end

            [rel_lvlh, ~] = rel_state_lvlh_local(X_chaser, X_target);
            hist = log_phase3_state_local(hist, X_chaser, X_target, t0 + elapsed);
            return;
        end

        elapsed = elapsed + dt_step;
        X_chaser = X_next;
        X_target = T_next;
        rel_prev = rel_next;
        hist = log_phase3_state_local(hist, X_chaser, X_target, t0 + elapsed);
    end

    error('R_BAR_200_FPA did not reach target R-bar alignment within %.2f hours.', max_wait/3600);
end

function tf = is_below_target_rbar_local(rel_lvlh, X_chaser, X_target, radial_tol)
    radial_gap = norm(X_target(1:3)) - norm(X_chaser(1:3));
    tf = rel_lvlh(1) < 0 && abs(rel_lvlh(1) + radial_gap) <= radial_tol;
end

function [X_cross, T_cross, t_cross] = refine_vbar_crossing_local(X0, T0, y0, dt_window, sys, t_abs0)
    lo = 0;
    hi = dt_window;
    X_cross = X0;
    T_cross = T0;
    t_cross = 0;

    for iter = 1:40
        mid = 0.5 * (lo + hi);
        [X_mid, T_mid] = propagate_pair_state_only_full_local(X0, T0, mid, min(2, max(mid/10, 0.1)), sys, t_abs0);
        [rel_mid, ~] = rel_state_lvlh_local(X_mid, T_mid);

        if sign(rel_mid(2)) == sign(y0)
            lo = mid;
        else
            hi = mid;
            X_cross = X_mid;
            T_cross = T_mid;
            t_cross = mid;
        end
    end
end

function [X_chaser, X_target, hist, elapsed] = propagate_until_altitude_local(X_chaser, X_target, sys, target_alt, max_time, dt, t0)
    hist = init_phase3_hist_local();
    elapsed = 0;
    alt_prev = norm(X_chaser(1:3)) - sys.Re;

    if alt_prev <= target_alt
        hist = log_phase3_state_local(hist, X_chaser, X_target, t0);
        return;
    end

    while elapsed < max_time - 1e-12
        dt_step = min(dt, max_time - elapsed);
        X_prev = X_chaser;
        T_prev = X_target;

        [X_next, T_next] = rk4_pair_step_full_local(X_prev, T_prev, dt_step, sys, t0 + elapsed);
        alt_next = norm(X_next(1:3)) - sys.Re;

        if alt_next <= target_alt
            [X_chaser, X_target, t_cross] = refine_altitude_crossing_local(X_prev, T_prev, target_alt, dt_step, sys, t0 + elapsed);
            elapsed = elapsed + t_cross;
            hist = log_phase3_state_local(hist, X_chaser, X_target, t0 + elapsed);
            return;
        end

        elapsed = elapsed + dt_step;
        X_chaser = X_next;
        X_target = T_next;
        hist = log_phase3_state_local(hist, X_chaser, X_target, t0 + elapsed);
    end

    error('Re-entry coast did not reach %.1f km altitude within %.2f min.', target_alt/1000, max_time/60);
end

function [X_cross, T_cross, t_cross] = refine_altitude_crossing_local(X0, T0, target_alt, dt_window, sys, t_abs0)
    lo = 0;
    hi = dt_window;
    X_cross = X0;
    T_cross = T0;
    t_cross = 0;

    for iter = 1:40
        mid = 0.5 * (lo + hi);
        [X_mid, T_mid] = propagate_pair_state_only_full_local(X0, T0, mid, min(1, max(mid/10, 0.05)), sys, t_abs0);
        alt_mid = norm(X_mid(1:3)) - sys.Re;

        if alt_mid > target_alt
            lo = mid;
        else
            hi = mid;
            X_cross = X_mid;
            T_cross = T_mid;
            t_cross = mid;
        end
    end
end

function [X_chaser, X_target] = propagate_pair_state_only_full_local(X_chaser, X_target, duration, dt, sys, t_abs0)
    if duration <= 0
        return;
    end

    elapsed = 0;
    while elapsed < duration - 1e-12
        dt_step = min(dt, duration - elapsed);
        [X_chaser, X_target] = rk4_pair_step_full_local(X_chaser, X_target, dt_step, sys, t_abs0 + elapsed);
        elapsed = elapsed + dt_step;
    end
end

function [X_chaser, X_target] = rk4_pair_step_full_local(X_chaser, X_target, dt_step, sys, t_abs)
    X_t_state = [X_target; zeros(7,1); sys.Target_Mass];
    k1_t = Env_EOM(t_abs,             X_t_state,                [0;0;0], [0;0;0], sys, false);
    k2_t = Env_EOM(t_abs+dt_step/2,   X_t_state+k1_t*dt_step/2, [0;0;0], [0;0;0], sys, false);
    k3_t = Env_EOM(t_abs+dt_step/2,   X_t_state+k2_t*dt_step/2, [0;0;0], [0;0;0], sys, false);
    k4_t = Env_EOM(t_abs+dt_step,     X_t_state+k3_t*dt_step,   [0;0;0], [0;0;0], sys, false);
    X_target = X_target + (dt_step/6)*(k1_t(1:6) + 2*k2_t(1:6) + 2*k3_t(1:6) + k4_t(1:6));

    k1 = Env_EOM(t_abs,             X_chaser,             [0;0;0], [0;0;0], sys, true);
    k2 = Env_EOM(t_abs+dt_step/2,   X_chaser+k1*dt_step/2,[0;0;0], [0;0;0], sys, true);
    k3 = Env_EOM(t_abs+dt_step/2,   X_chaser+k2*dt_step/2,[0;0;0], [0;0;0], sys, true);
    k4 = Env_EOM(t_abs+dt_step,     X_chaser+k3*dt_step,  [0;0;0], [0;0;0], sys, true);
    X_chaser = X_chaser + (dt_step/6)*(k1 + 2*k2 + 2*k3 + k4);

    if norm(X_chaser(7:10)) > 0
        X_chaser(7:10) = X_chaser(7:10) / norm(X_chaser(7:10));
    end
end

function n = orbit_rate_from_state_local(X)
    r = X(1:3);
    v = X(4:6);
    n = norm(cross(r, v)) / norm(r)^2;
end

function value = get_phase3_param_local(s, name, default_value)
    if isstruct(s) && isfield(s, name) && ~isempty(s.(name))
        value = s.(name);
    else
        value = default_value;
    end
end

function value = get_phase3_bool_param_local(s, name, default_value)
    if isstruct(s) && isfield(s, name) && ~isempty(s.(name))
        value = parse_bool_setting_local(s.(name));
    else
        value = default_value;
    end
end

function value = parse_bool_setting_local(raw_value)
    if islogical(raw_value)
        value = raw_value;
        return;
    end

    if isnumeric(raw_value) && isscalar(raw_value)
        value = raw_value ~= 0;
        return;
    end

    text_value = lower(strtrim(string(raw_value)));
    if any(text_value == ["1", "true", "yes", "y", "on"])
        value = true;
    elseif any(text_value == ["0", "false", "no", "n", "off"])
        value = false;
    else
        error('Boolean setting must be true/false, on/off, yes/no, or 1/0. Got: %s', string(raw_value));
    end
end

function label = bool_label_local(value)
    if value
        label = "on";
    else
        label = "off";
    end
end

function hist = init_phase3_hist_local()
    hist.pos = [];
    hist.vel = [];
    hist.mass = [];
    hist.time = [];
    hist.time_end = 0;
    hist.target_pos = [];
    hist.target_vel = [];
    hist.rel_pos = [];
    hist.rel_pos_lvlh = [];
    hist.rel_vel_lvlh = [];
end

function hist = log_phase3_state_local(hist, X_chaser, X_target, t)
    if ~isfield(hist, 'time')
        hist = init_phase3_hist_local();
    end

    hist.pos = [hist.pos, X_chaser(1:3)];
    hist.vel = [hist.vel, X_chaser(4:6)];
    hist.mass = [hist.mass, X_chaser(14)];
    hist.time = [hist.time, t];
    hist.time_end = t;

    if ~isempty(X_target)
        hist.target_pos = [hist.target_pos, X_target(1:3)];
        hist.target_vel = [hist.target_vel, X_target(4:6)];
        hist.rel_pos = [hist.rel_pos, X_chaser(1:3) - X_target(1:3)];
        [rel_lvlh, rel_vel_lvlh] = rel_state_lvlh_local(X_chaser, X_target);
        hist.rel_pos_lvlh = [hist.rel_pos_lvlh, rel_lvlh];
        hist.rel_vel_lvlh = [hist.rel_vel_lvlh, rel_vel_lvlh];
    end
end

function hist = append_phase3_hist_local(hist, sub_hist)
    if isempty(sub_hist) || ~isfield(sub_hist, 'time') || isempty(sub_hist.time)
        return;
    end

    if ~isfield(hist, 'time') || isempty(hist.time)
        hist = sub_hist;
        if ~isfield(hist, 'time_end')
            hist.time_end = hist.time(end);
        end
        return;
    end

    fields = {'pos','vel','mass','time','target_pos','target_vel','rel_pos','rel_pos_lvlh','rel_vel_lvlh'};
    for ii = 1:numel(fields)
        f = fields{ii};
        if ~isfield(hist, f)
            hist.(f) = [];
        end
        if isfield(sub_hist, f) && ~isempty(sub_hist.(f))
            hist.(f) = [hist.(f), sub_hist.(f)];
        end
    end
    hist.time_end = hist.time(end);
end
