function entry = entry_state(case_id, cfg)
%ENTRY_STATE Construct a Table-4 entry state under explicit conventions.
%   The 14-element state is compatible with the existing project
%   Reentry_Propagator. Published longitude/latitude are treated as
%   spherical Earth-fixed coordinates at an artificial t=0 where ECI and
%   Earth-fixed axes coincide. Atmospheric rotation is added to the
%   published ground-relative velocity to form ECI velocity.

    if nargin < 2 || isempty(cfg)
        cfg = paperstudies.saito.config();
    end
    if ~isscalar(case_id) || ~isfinite(case_id) || ...
            case_id ~= fix(case_id) || case_id < 1 || case_id > 4
        error('paperstudies:saito:entry_state:InvalidCase', ...
              'case_id must be an integer from 1 through 4.');
    end

    row = cfg.tables.table4.values(case_id, :);
    altitude_m = row(1) * 1e3;
    longitude_rad = deg2rad(row(2));
    latitude_rad = deg2rad(row(3));
    speed_m_s = row(4) * 1e3;
    fpa_rad = deg2rad(row(5));
    azimuth_rad = deg2rad(row(6));
    published_range_m = row(7) * 1e3;

    r_hat = [cos(latitude_rad) * cos(longitude_rad); ...
             cos(latitude_rad) * sin(longitude_rad); ...
             sin(latitude_rad)];
    north_hat = [-sin(latitude_rad) * cos(longitude_rad); ...
                 -sin(latitude_rad) * sin(longitude_rad); ...
                  cos(latitude_rad)];
    east_hat = [-sin(longitude_rad); cos(longitude_rad); 0];

    radius_m = cfg.conventions.earth_radius_m + altitude_m;
    position_eci_m = radius_m * r_hat;
    horizontal_hat = cos(azimuth_rad) * north_hat + ...
                     sin(azimuth_rad) * east_hat;
    velocity_relative_m_s = speed_m_s * ( ...
        sin(fpa_rad) * r_hat + cos(fpa_rad) * horizontal_hat);
    omega_earth = [0; 0; cfg.conventions.earth_rotation_rad_s];
    velocity_eci_m_s = velocity_relative_m_s + ...
        cross(omega_earth, position_eci_m);

    X14 = zeros(14,1);
    X14(1:3) = position_eci_m;
    X14(4:6) = velocity_eci_m_s;
    X14(7:10) = [0;0;0;1];
    X14(14) = cfg.tables.table1.capsule.mass_kg;

    roundtrip = paperstudies.saito.roundtrip_entry_state(X14, cfg);
    [computed_range_m, central_angle_rad] = ...
        paperstudies.saito.eq14_range_to_go( ...
            latitude_rad, longitude_rad, ...
            deg2rad(cfg.tables.table4.target_latitude_deg), ...
            deg2rad(cfg.tables.table4.target_longitude_deg), ...
            cfg.conventions.earth_radius_m);

    entry.case_id = case_id;
    entry.frame = cfg.conventions.entry_epoch_frame;
    entry.latitude_interpretation = cfg.conventions.entry_latitude_interpretation;
    entry.X_eci_14 = X14;
    entry.published = struct( ...
        'altitude_m', altitude_m, ...
        'longitude_deg', row(2), ...
        'latitude_deg', row(3), ...
        'speed_m_s', speed_m_s, ...
        'fpa_deg', row(5), ...
        'azimuth_deg', row(6), ...
        'range_to_go_m', published_range_m);
    entry.roundtrip = roundtrip;
    entry.roundtrip_error = struct( ...
        'altitude_m', roundtrip.altitude_m - altitude_m, ...
        'longitude_deg', wrap_degrees(roundtrip.longitude_deg - row(2)), ...
        'latitude_deg', roundtrip.latitude_deg - row(3), ...
        'speed_m_s', roundtrip.speed_relative_m_s - speed_m_s, ...
        'fpa_deg', roundtrip.fpa_deg - row(5), ...
        'azimuth_deg', wrap_degrees(roundtrip.azimuth_deg - row(6)));
    entry.range_diagnostic = struct( ...
        'central_angle_rad', central_angle_rad, ...
        'computed_standard_radius_m', computed_range_m, ...
        'published_m', published_range_m, ...
        'difference_m', published_range_m - computed_range_m, ...
        'effective_radius_to_match_published_m', published_range_m / central_angle_rad, ...
        'inconsistency_detected', abs(published_range_m - computed_range_m) > 1e3, ...
        'classification', "CONVENTION_REQUIRED");
end

function angle_deg = wrap_degrees(angle_deg)
    angle_deg = mod(angle_deg + 180, 360) - 180;
end
