function manifest = status()
%STATUS Machine-readable reproduction scope for the Saito paper study.

    manifest.study_id = "SAITO_2025_ACTA_ASTRONAUTICA_229_684_697";
    manifest.overall = "PARTIAL_REPRODUCTION";
    manifest.full_numeric_reproduction_possible = false;
    manifest.surrogate_forward_propagation_available = true;
    manifest.surrogate_is_numeric_paper_reproduction = false;

    manifest.classifications = struct( ...
        'published_exact', "PUBLISHED_EXACT", ...
        'convention_required', "CONVENTION_REQUIRED", ...
        'surrogate_only', "SURROGATE_ONLY", ...
        'unavailable', "UNAVAILABLE");

    manifest.items = [ ...
        item("TABLES_1_3_4_5_6_7_8_9_10_11", "PUBLISHED_EXACT", ...
             "Values transcribed from the published tables."), ...
        item("TABLE6_IGNITION_TIME_GRID", "PUBLISHED_EXACT", ...
             "The 27 ignition epochs follow exactly from the printed start, end, and 30 s interval."), ...
        item("TABLE6_INDIVIDUAL_ENTRY_STATES_AND_RANGES", "UNAVAILABLE", ...
             "Only aggregate 2369-7031 km bounds and approximate spacing are printed; individual values are not synthesized."), ...
        item("DYNAMICS_AND_AERO_EQS_10_TO_12_AND_26", "PUBLISHED_EXACT", ...
             "The public spherical dynamics, force, and CA/CN transformation algebra is represented."), ...
        item("GUIDANCE_EQS_13_TO_16_23_TO_25", "PUBLISHED_EXACT", ...
             "Algebra is public; omitted gains and scheduling remain separate blockers."), ...
        item("GUIDANCE_EQS_17_TO_22", "CONVENTION_REQUIRED", ...
             "Algebra is public, but Eq. 17 lacks distance redimensionalization and V0/K1/K2/K3 are unpublished."), ...
        item("ENTRY_SWITCHES_AND_RATES", "PUBLISHED_EXACT", ...
             "0.20 g activation, Mach 3 cutoff, 240 m/s termination, and published execution rates."), ...
        item("TABLE4_SPHERICAL_STATE_CONSTRUCTION", "CONVENTION_REQUIRED", ...
             "The paper labels geodetic coordinates while using a spherical-Earth entry model."), ...
        item("TABLE4_RANGE_TO_GO_RECOMPUTATION", "CONVENTION_REQUIRED", ...
             "Printed coordinates and target do not reproduce the printed range-to-go with a standard Earth radius."), ...
        item("TABLE5_INTERPOLATION_AND_DISTANCE_SCALING", "CONVENTION_REQUIRED", ...
             "Interpolation is unspecified and Eqs. 14/17 omit the distance scaling needed by the km-valued table."), ...
        item("CONSTANT_CD_LD_FORWARD_TRAJECTORY", "SURROGATE_ONLY", ...
             "Uses published mass/area/baseline Cd with an assumed constant L/D; it cannot reproduce HSRC aerodynamics."), ...
        item("SUTTON_GRAVES_HEATING", "SURROGATE_ONLY", ...
             "The existing propagator heating law is not the paper's Eq. 28."), ...
        item("HSRC_CA_CN_DATABASE", "UNAVAILABLE", ...
             "The Mach/AoA axial and normal coefficient database is proprietary and not printed."), ...
        item("FULL_CROSSRANGE_AND_TERMINAL_GUIDANCE", "UNAVAILABLE", ...
             "Deadband schedule, estimator beta, predictor perturbation, transition, and controller settings are omitted."), ...
        item("FULL_SIX_DOF_DEORBIT_REPRODUCTION", "UNAVAILABLE", ...
             "RCS directions, RW/RCS gains, phase durations, and several environment implementation details are omitted."), ...
        item("PAPER_EQ28_NUMERIC_HEATING", "UNAVAILABLE", ...
             "Nose radius, stagnation-state calculation, and coefficient unit convention are insufficiently specified.")];

    manifest.blockers = [ ...
        blocker("HSRC_CA_CN_DATABASE", "Provide the JAXA/ElevationSpace Mach-AoA CA/CN tables."), ...
        blocker("MACH10_TRIM_AOA", "Provide the trim angle or trim model used before guidance activation."), ...
        blocker("EXPLICIT_GUIDANCE_V0_AND_BIAS_FACTORS", "Provide V0, K1, K2, K3, and the Eq. 17 distance redimensionalization convention."), ...
        blocker("TABLE6_INDIVIDUAL_ENTRY_CASES", "Provide the 27 exact entry states/range-to-go values; only bounds are published."), ...
        blocker("CROSSRANGE_DEADBAND_SCHEDULE", "Provide velocity gain/bias and reversal logic."), ...
        blocker("FADING_FILTER_BETA", "Provide beta and estimator initialization for Eq. 24."), ...
        blocker("RPC_PREDICTOR_SETTINGS", "Provide delta-sigma, predictor terminal event, step, bounds, and command sign convention."), ...
        blocker("TERMINAL_BANK_SWITCH", "Provide the transition criterion and secant initial guesses/iteration limits."), ...
        blocker("RCS_AND_RW_CONTROL", "Provide thrust directions, PID gains, valve dynamics, RW limits, and phase timing."), ...
        blocker("DETRA_KEMP_RIDDELL_INPUTS", "Provide Rn, stagnation enthalpy model, V0 convention, and units for Eq. 28.")];

    manifest.allowed_claims = [ ...
        "Published constants and equations are represented auditably.", ...
        "Table-4 entry states, Table-6 ignition epochs, and uncertainty case grids are reproducible.", ...
        "A reduced constant-Cd/L/D trajectory can exercise the shared propagator.", ...
        "Synthetic equation and coordinate round-trip regressions can verify implementation consistency."];
    manifest.disallowed_claims = [ ...
        "The surrogate reproduces the paper landing dispersions.", ...
        "Agreement after tuning a surrogate to Tables 8/10/11 is independent validation.", ...
        "The current heating result verifies the paper's thermal constraint.", ...
        "The full 6-DOF deorbit or proprietary HSRC aerodynamic model is implemented."];
end

function value = item(id, classification, rationale)
    value = struct('id', id, 'classification', classification, ...
                   'rationale', rationale);
end

function value = blocker(id, required_input)
    value = struct('id', id, 'required_input', required_input);
end
